// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVoFIGLQ7G7HKSKdtmqQqCoWn3fhgvuqE',
    appId: '1:140339280728:web:5554b94abb9ae0ffcbc32d',
    messagingSenderId: '140339280728',
    projectId: 'fir-test-4370f',
    authDomain: 'fir-test-4370f.firebaseapp.com',
    storageBucket: 'fir-test-4370f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2X7LH2C93gPvgic8lqy3QAnCNci18apQ',
    appId: '1:140339280728:android:9cf38b9647373510cbc32d',
    messagingSenderId: '140339280728',
    projectId: 'fir-test-4370f',
    storageBucket: 'fir-test-4370f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_epiZec_KXMDiX5Uhxq6DaR5aa9pv_bQ',
    appId: '1:140339280728:ios:8db006264c51076dcbc32d',
    messagingSenderId: '140339280728',
    projectId: 'fir-test-4370f',
    storageBucket: 'fir-test-4370f.appspot.com',
    iosClientId: '140339280728-gdmdpje0c7h65ol8k0dn9ug68k78ibs5.apps.googleusercontent.com',
    iosBundleId: 'com.devchief',
  );
}
